name: Build and push Docker image

on:
  workflow_call:
    inputs:
      context:
        description: "Path to the Dockerfile directory to build"
        default: "."
        type: string
      image-path:
        description: "Path of the docker image Tag"
        default: "ghcr.io/${{ github.repository }}/app"
        type: string

jobs:
  container-image-build:
    name: Docker
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - id: format
        name: Lowercase repository path
        uses: ASzc/change-string-case-action@v1
        with:
          string: ${{ inputs.image-path }}
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        if: ${{ github.event_name == 'release' || github.event_name == 'push'  }}
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build  (pull request)
        uses: docker/build-push-action@v6
        if: ${{ github.event_name == 'pull_request'}}
        with:
          context: "{{defaultContext}}:${{ inputs.context }}"
          tags: "${{ steps.format.outputs.lowercase }}:develop"
          push: false
      - name: Build and push (develop)
        uses: docker/build-push-action@v6
        if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/develop' }}
        with:
          context: "{{defaultContext}}:${{ inputs.context }}"
          tags: "${{ steps.format.outputs.lowercase }}:develop"
          push: true
      - name: Build and push (main)
        uses: docker/build-push-action@v6
        if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
        with:
          context: "{{defaultContext}}:${{ inputs.context }}"
          tags: "${{ steps.format.outputs.lowercase }}:latest"
          push: true
      - name: Build and push (release)
        uses: docker/build-push-action@v6
        if: ${{ github.event_name == 'release' }}
        with:
          context: "{{defaultContext}}:${{ inputs.context }}"
          tags: "${{ steps.format.outputs.lowercase }}:${{ github.ref_name }}"
          push: true
